[project]
name = 'AdStack'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ad-content-registry]
path = 'contracts/ad-content-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.analytics-aggregator]
path = 'contracts/analytics-aggregator.clar'
clarity_version = 4
epoch = 'latest'

[contracts.auction-system]
path = 'contracts/auction-system.clar'
clarity_version = 4
epoch = 'latest'

[contracts.campaign-orchestrator]
path = 'contracts/campaign-orchestrator.clar'
clarity_version = 4
epoch = 'latest'

[contracts.dispute-resolution]
path = 'contracts/dispute-resolution.clar'
clarity_version = 4
epoch = 'latest'

[contracts.escrow-manager]
path = 'contracts/escrow-manager.clar'
clarity_version = 4
epoch = 'latest'

[contracts.governance-dao]
path = 'contracts/governance-dao.clar'
clarity_version = 4
epoch = 'latest'

[contracts.oracle-integration]
path = 'contracts/oracle-integration.clar'
clarity_version = 4
epoch = 'latest'

[contracts.revenue-settlement]
path = 'contracts/revenue-settlement.clar'
clarity_version = 4
epoch = 'latest'

[contracts.publisher-network]
path = 'contracts/publisher-network.clar'
clarity_version = 4
epoch = 'latest'

[contracts.rewards-distributor]
path = 'contracts/rewards-distributor.clar'
clarity_version = 4
epoch = 'latest'

[contracts.subscription-manager]
path = 'contracts/subscription-manager.clar'
clarity_version = 4
epoch = 'latest'

[contracts.targeting-engine]
path = 'contracts/targeting-engine.clar'
clarity_version = 4
epoch = 'latest'

[contracts.identity-registry]
path = 'contracts/identity-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.fraud-prevention]
path = 'contracts/fraud-prevention.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
